### ISSUE TITLE
Unable to submit this package to packagist

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store_bcc_payway#1]
I'm unable to submit this package tp packagist: I see this error:

> The vendor name "concretecms-community-store" was already claimed by someone else on Packagist.org.
> You may ask them to add your package and give you maintainership access.
> If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace.
> The packages already in that vendor namespace can be found at [concretecms-community-store](https://packagist.org/packages/concretecms-community-store/).

@Mesuva I guess that in order to add this community_store_bcc_payway package to packagist I'd need that you:
1. [submit](https://packagist.org/packages/submit) this repository ( https://github.com/concretecms-community-store/community_store_bcc_payway ) to packagist.org
2. go to the newly submitted packagist page (should be https://packagist.org/packages/concretecms-community-store/community_store_bcc_payway )
3. add me (`mlocati`) as the maintainer for it by clickin the `+` icon under the Maintainers section you find top right in the page

**Comment by Mesuva** [comment]
Yes, I started to set things up yesterday.
I've added this new repo, and have added you as a maintainer.

I've also added you as a maintainer of the main community store repo, in case you spot things there that are worth adjusting. But let me know if you'd like me to remove that access!  😄

**Comment by mlocati** [comment]
Thanks Ryan!
PS: there's no problem keeping me as a maintainer of the main repo: I promise I won't destroy anything :wink:
